services:
  - docker

branches:
  only:
    - master

os:
  - linux

env:
  global:
    - DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
    - DATE_TM=`TZ=America/New_York date "+%m-%d-%y %H:%M"`
    - DOCKER_IMAGE="leanda/ui"

before_script:
  - echo "{\"buildInfo\":{\"buildId\":\""$TRAVIS_BUILD_NUMBER"\",\"buildDate\":\""$DATE_TM"\",\"environment\":\"DEV\"}}" > src/jenkinsBuildData.json
  - cat ./src/jenkinsBuildData.json

script:
  - docker build --build-arg APP_ENV=deploy -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE # Pushes both date and latest
